### PR TITLE
Create intro.md

### PR DESCRIPTION
**Pull request by rroojrooj**
Please give feedback on what to improve. Team members should know more than users, therefore, please check for the correctness of the information. Please tell me what is missing. Thank you.

### CODE REVIEW

**Comment by rhlsthrm** [comment]
This information is no longer true with the Amarok upgrade. It will need to be updated to reflect the current system.

**Comment by rroojrooj** [comment]
Okay and thank you Rahul for your comments. I will do more research and I will update the docs to match the current version. If I have any questions, can I text you in discord? It may take time to understand all the working mechanisms. Thanks again, Rooj.

**Comment by rhlsthrm** [comment]
> Okay and thank you Rahul for your comments. I will do more research and I will update the docs to match the current version. If I have any questions, can I text you in discord? It may take time to understand all the working mechanisms. Thanks again, Rooj.

Of course you can text in Discord!

**Comment by rroojrooj** [comment]
Updated version. Once again, please give feedback and check for the correctness of the information. Also, please tell me which part should focus on more and what is missing. Thank you.

**Comment by rroojrooj** [comment]
I think that the 'checklist.md' file name is wrong, it should not be 'intro.md'.

**Review by VArtOff — CHANGES_REQUESTED** [review]
Topic "What are Routers?"

Routers in the Connext project are the key link after the user. They can be categorised as an active LP provider because the router is able to adapt to the current market realities.
The main task of the router is to provide liquidity to the different networks so that Connext users can make cross-chain swaps quickly and cheaply.
The only way for them to earn money is through commissions, which depend on the total amount of the transaction. But they can't get them right away, because thanks to the partnership with Nomad, users don't have to worry about things like shunning attacks(regular users won't be able to face a conspiracy between routers because of a 30 minute delay in getting commission rewards).

**Pull request merged**
