### PR TITLE
Add Thai Language supports for documentation

### PR DESCRIPTION
**Pull request by tann9949**
- I've add a Thai language version of a documentation
- Adding locale for Thai language and English Language (Eng is default language)

### CODE REVIEW

**Comment by rhlsthrm** [comment]
Hi @tann9949 we made some changes to the docs! Can you please update your branch?

**Comment by tann9949** [comment]
Documentation updated as well as for the Thai version!

**Comment by duckdegen** [comment]
Will rewrite lots of the documentation, so dropping this for now. Thanks for the contribution. Can we ping you in the future if we need translation work?

**Comment by tann9949** [comment]
@duckdegen Yeah sure!

**Comment by rroojrooj** [comment]
ถ้าอยากให้ช่วยติดต่อมาได้นะครับ

**Pull request closed without merging**
